chore!: Bump `rustc` to `1.83.0`
`1.82.0` doesn’t compile anymore:

```log
error: rustc 1.82.0 is not supported by the following packages:
  icu_collections@2.1.1 requires rustc 1.83
  icu_locale_core@2.1.1 requires rustc 1.83
  icu_normalizer@2.1.1 requires rustc 1.83
  icu_normalizer_data@2.1.1 requires rustc 1.83
  icu_normalizer_data@2.1.1 requires rustc 1.83
  icu_normalizer_data@2.1.1 requires rustc 1.83
  icu_properties@2.1.1 requires rustc 1.83
  icu_properties_data@2.1.1 requires rustc 1.83
  icu_properties_data@2.1.1 requires rustc 1.83
  icu_properties_data@2.1.1 requires rustc 1.83
  icu_provider@2.1.1 requires rustc 1.83
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.82.0
```